---
- name: Fact dump
  hosts: web1
  tasks:
    - name: Print all facts
      debug:
        msg: >
          The default IPv4 address of {{ ansible_facts.system }}
          is {{ ansible_facts.all_ipv4_addresses }}

...
